#!/bin/bash

sed -i "s|{image}|$IMAGE_NAME|g" manifest.yaml
sed -i "s|{tag}|$DOCKER_TAG|g" manifest.yaml

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-amd64
chmod +x manifest-tool

./manifest-tool push from-spec manifest.yaml
