#!/usr/bin/with-contenv bash

# permissions
chown -R abc:abc \
	/hath/data \
	/hath/log

# Create client_login if it doesn't exist yet
if [ ! -f /hath/data/client_login ]; then
	printf "${HATH_CLIENT_ID}-${HATH_CLIENT_KEY}" >> /hath/data/client_login
fi
